Fix remove whitelines as Tony requested
angsa-robotics/RTK_GPS_NTRIP pull request #7
Opened 2024-04-17 09:04 UTC by AlboAlby00

2024-04-17 11:28 UTC, tonynajjar commented
Like this it'll be hard to comment on what's missing because the changes are already made. Can we do it the other way around aka cleanup all the changes on main and open a PR with only the required changes?

2024-04-17 12:19 UTC, AlboAlby00 commented
> Like this it'll be hard to comment on what's missing because the changes are already made. Can we do it the other way around aka cleanup all the changes on main and open a PR with only the required changes?

I'm not sure if I understood this comment correctly, but it is possible to see all the differences between the fix-remove-whitelines branch in the Angsa forked repo and the main branch at olvdhrm repo here. https://github.com/olvdhrm/RTK_GPS_NTRIP/compare/main...angsa-robotics:RTK_GPS_NTRIP:fix-remove-whitelines

2024-04-18 09:08 UTC, karl-schulz requested changes

2024-04-18 09:08 UTC, karl-schulz commented on ublox_gps/src/node.cpp
> +  this->declare_parameter("ntrip_corrections", false);
Do we really need this parameter?

2024-04-18 09:38 UTC, AlboAlby00 commented on ublox_gps/src/node.cpp
> +  this->declare_parameter("ntrip_corrections", false);
We do for the heading kit, since otherwise the rover receives correction both through the /ntrip_client/rtcm topic both through the moving_base, so we need it to ignore the /ntrip_client/rtcm topic

2024-04-18 09:43 UTC, tonynajjar commented
> I'm not sure if I understood this comment correctly, but it is possible to see all the differences between the fix-remove-whitelines branch in the Angsa forked repo and the main branch at olvdhrm repo here. [olvdhrm/RTK_GPS_NTRIP@main...angsa-robotics:RTK_GPS_NTRIP:fix-remove-whitelines](https://github.com/olvdhrm/RTK_GPS_NTRIP/compare/main...angsa-robotics:RTK_GPS_NTRIP:fix-remove-whitelines)

I'll give you an example: I can't comment on this PR to say "remove __pycache__ from gitignore" because it's not in this PR. I'd need to reference the other one. It would be easier to just review everything in one PR.

2024-04-21 08:46 UTC, karl-schulz commented on ublox_gps/src/node.cpp
> +  this->declare_parameter("ntrip_corrections", false);
Can't we just remap the topic for one of the modues?

2024-04-22 08:46 UTC, closed without merging

2024-04-25 06:49 UTC, karl-schulz commented on ublox_gps/src/node.cpp
> +  this->declare_parameter("ntrip_corrections", false);
@AlboAlby00 ?

2024-04-25 06:50 UTC, karl-schulz commented
Hey @AlboAlby00  I see you put all the changes in one commit and force-pushed this.

It's good to put everything in one commit, but this commit should have been in a separate branch with a proper PR. The `main` branch should not be committed to directly. Also There are obviously still whitespace changes w.r.t. upstream:
https://github.com/olvdhrm/RTK_GPS_NTRIP/compare/main...angsa-robotics:RTK_GPS_NTRIP:main
![image](https://github.com/angsa-robotics/RTK_GPS_NTRIP/assets/12829107/329c1c9d-c610-4205-b840-05b92eee3796)
![image](https://github.com/angsa-robotics/RTK_GPS_NTRIP/assets/12829107/f1ccedc3-2501-4743-9abf-06b217e2d881)

And the topic is again changed:
![image](https://github.com/angsa-robotics/RTK_GPS_NTRIP/assets/12829107/1eba712d-1c6e-4bf3-a1cf-0261942e4582)

That is why we do PRs and merge all the changes in one squash commit. Only changes that OK are committed this way, and only the relevant diff is squashed together.

You also did not respond to my question if the parameter is really required - we can also just rewire the topic in the launch file to point to something else.

2024-04-25 08:10 UTC, tonynajjar commented
> It's good to put everything in one commit, but this commit should have been in a separate branch with a proper PR. The main branch should not be committed to directly. Also There are obviously still whitespace changes w.r.t. upstream:

@karl-schulz the force-pushing to main was allowed by me exceptionally (although it's generally a bad idea). Here is some context: I asked that the fork be reverted to its original state and that one PR be created with only the necessary changes. Main could have been reverted without force-pushing but Alberto wanted to have a clean history so I allowed it (given it's not a critical repo).

@AlboAlby00 however looks like things didn't go to plan? main still differs from upstream and there was no PR with the changes we need?

I suggest with take 10 mins to "pair git/program" this. @AlboAlby00 ping me when you can work on this again

2024-04-25 09:18 UTC, karl-schulz commented
Had the same idea and did a quick session with Alberto.